// generated by stringer -type=PhaseKind; DO NOT EDIT

package gcstats

import "fmt"

const _PhaseKind_name = "PhaseSweepTermPhaseScanPhaseInstallWBPhaseMarkPhaseMarkTermPhaseSweepPhaseMultiple"

var _PhaseKind_index = [...]uint8{0, 14, 23, 37, 46, 59, 69, 82}

func (i PhaseKind) String() string {
	if i < 0 || i+1 >= PhaseKind(len(_PhaseKind_index)) {
		return fmt.Sprintf("PhaseKind(%d)", i)
	}
	return _PhaseKind_name[_PhaseKind_index[i]:_PhaseKind_index[i+1]]
}
